"""Schema definitions for Productive reference/lookup tables (full sync)."""


def get_reference_schema() -> list:
    """Return schema list for all reference tables."""
    return [
        {"table": "organizations", "primary_key": ["id"]},
        {"table": "subsidiaries", "primary_key": ["id"]},
        {"table": "custom_fields", "primary_key": ["id"]},
        {"table": "custom_field_options", "primary_key": ["id"]},
        {"table": "custom_field_sections", "primary_key": ["id"]},
        {"table": "tags", "primary_key": ["id"]},
        {"table": "service_types", "primary_key": ["id"]},
        {"table": "deal_statuses", "primary_key": ["id"]},
        {"table": "lost_reasons", "primary_key": ["id"]},
        {"table": "workflows", "primary_key": ["id"]},
        {"table": "workflow_statuses", "primary_key": ["id"]},
        {"table": "pipelines", "primary_key": ["id"]},
        {"table": "events", "primary_key": ["id"]},
        {"table": "holiday_calendars", "primary_key": ["id"]},
        {"table": "holidays", "primary_key": ["id"]},
        {"table": "document_types", "primary_key": ["id"]},
        {"table": "document_styles", "primary_key": ["id"]},
        {"table": "approval_policies", "primary_key": ["id"]},
        {"table": "approval_workflows", "primary_key": ["id"]},
        {"table": "approval_policy_assignments", "primary_key": ["id"]},
        {"table": "rate_cards", "primary_key": ["id"]},
        {"table": "tax_rates", "primary_key": ["id"]},
        {"table": "exchange_rates", "primary_key": ["id"]},
        {"table": "bank_accounts", "primary_key": ["id"]},
        {"table": "invoice_templates", "primary_key": ["id"]},
        {"table": "automatic_invoicing_rules", "primary_key": ["id"]},
        {"table": "payment_reminders", "primary_key": ["id"]},
        {"table": "payment_reminder_sequences", "primary_key": ["id"]},
        {"table": "deal_cost_rates", "primary_key": ["id"]},
        {"table": "kpd_codes", "primary_key": ["id"]},
        {"table": "report_categories", "primary_key": ["id"]},
        {"table": "service_assignments", "primary_key": ["id"]},
        {"table": "service_type_assignments", "primary_key": ["id"]},
        {"table": "time_tracking_policies", "primary_key": ["id"]},
        {"table": "teams", "primary_key": ["id"]},
        {"table": "team_memberships", "primary_key": ["id"]},
        {"table": "sections", "primary_key": ["id"]},
        {"table": "folders", "primary_key": ["id"]},
        {"table": "organization_memberships", "primary_key": ["id"]},
        {"table": "integration_exporter_configurations", "primary_key": ["id"]},
        {"table": "integrations", "primary_key": ["id"]},
    ]
