"""Schema definitions for Productive data tables (incremental + full sync)."""


def get_data_schema() -> list:
    """Return schema list for all data tables."""
    return [
        # Incremental tables (have date-based filters)
        {"table": "time_entries", "primary_key": ["id"]},
        {"table": "time_entry_versions", "primary_key": ["id"]},
        {"table": "bookings", "primary_key": ["id"]},
        {"table": "services", "primary_key": ["id"]},
        {"table": "activities", "primary_key": ["id"]},
        {"table": "salaries", "primary_key": ["id"]},
        # Full-sync tables
        {"table": "people", "primary_key": ["id"]},
        {"table": "users", "primary_key": ["id"]},
        {"table": "companies", "primary_key": ["id"]},
        {"table": "projects", "primary_key": ["id"]},
        {"table": "boards", "primary_key": ["id"]},
        {"table": "task_lists", "primary_key": ["id"]},
        {"table": "tasks", "primary_key": ["id"]},
        {"table": "task_dependencies", "primary_key": ["id"]},
        {"table": "deals", "primary_key": ["id"]},
        {"table": "contracts", "primary_key": ["id"]},
        {"table": "invoices", "primary_key": ["id"]},
        {"table": "invoice_attributions", "primary_key": ["id"]},
        {"table": "line_items", "primary_key": ["id"]},
        {"table": "payments", "primary_key": ["id"]},
        {"table": "expenses", "primary_key": ["id"]},
        {"table": "memberships", "primary_key": ["id"]},
        {"table": "comments", "primary_key": ["id"]},
        {"table": "attachments", "primary_key": ["id"]},
        {"table": "contact_entries", "primary_key": ["id"]},
        {"table": "pages", "primary_key": ["id"]},
        {"table": "page_versions", "primary_key": ["id"]},
        {"table": "dashboards", "primary_key": ["id"]},
        {"table": "filters", "primary_key": ["id"]},
        {"table": "prices", "primary_key": ["id"]},
        {"table": "entitlements", "primary_key": ["id"]},
        {"table": "timers", "primary_key": ["id"]},
        {"table": "timesheets", "primary_key": ["id"]},
        {"table": "overheads", "primary_key": ["id"]},
        {"table": "revenue_distributions", "primary_key": ["id"]},
        {"table": "placeholders", "primary_key": ["id"]},
        {"table": "purchase_orders", "primary_key": ["id"]},
        {"table": "bills", "primary_key": ["id"]},
        {"table": "todos", "primary_key": ["id"]},
        {"table": "discussions", "primary_key": ["id"]},
        {"table": "proposals", "primary_key": ["id"]},
        {"table": "emails", "primary_key": ["id"]},
        {"table": "deleted_items", "primary_key": ["id"]},
        {"table": "surveys", "primary_key": ["id"]},
        {"table": "survey_fields", "primary_key": ["id"]},
        {"table": "survey_field_options", "primary_key": ["id"]},
        {"table": "survey_responses", "primary_key": ["id"]},
        {"table": "resource_requests", "primary_key": ["id"]},
        {"table": "pulses", "primary_key": ["id"]},
        {"table": "widgets", "primary_key": ["id"]},
    ]
